### ISSUE TITLE
Ok button not enabling with data in field

### ISSUE THREAD

**Issue by mitch-besser** [ElectronicControlsDesign/LoginDialog#7]
This bug may be solved when the Username is selected. The requirement is for the Ok button to be enabled if and only if a Username is selected and the Password field is not empty. The Green color is only used when the Password data is correct.

**Comment by dbaltimore** [comment]
I fixed this with the last push.

**Comment by mitch-besser** [comment]
@dbaltimore, I'm not seeing the code changed. Try pushing again and/or verify the code changes are on the master branch.

**Comment by mitch-besser** [comment]
@dbaltimore still not fixed. Make sure you read the issue description and fully understand it. You seem confused. There are 2 validations. One is a field validation, the other is a form validation.

**Comment by dbaltimore** [comment]
I'm only fixing problems you are having.  You needed the OK button to enable on correct password entry. I did that. Your form level validate is a different matter that does need coding.  

In my original sample, I had the drop down list with a blank entry to start,  QML has two modes,  Type entry and selection from the list or selection from the list only.  It is currently set for the latter. The first entry will always show.  You have to add a blank entry or "Select your User here" and validate that they have selected a choice and it's not blank or "Select your User here".  I was originally contacted to act as an advisor in QT/QML so that has been the position I have taken.  I'd be happy to code it for you but I need to know what you want to do about the control. enable typing or add to the list the default start item.

**Comment by mitch-besser** [comment]
@dbaltimore "You needed the OK button to enable on correct password entry."

You are not correct. 

From the Dec 6th posting of the specification:

If a username is selected and the password field has any characters in it, the Ok button will be enabled, otherwise the Ok button is disabled.

The code does not do this. Read the issue again. 

The requirement is for the Ok button to be enabled if and only if a Username is selected and the Password field is not empty. The Green color is only used when the Password data is correct.
